common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  username: root
  password: RathanakPassword

development:
  <<: *common
  database: my_tob_develop

test:
  <<: *common
  database: my_tob_test

staging:
  <<: *common
  database: my_tob_staging

production:
  <<: *common
  database: my_tob_production